name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # execute every 12 hours
    - cron: '* */24 * * *'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: npm run prod